main: "${project.groupId}.${project.name}"
name: "${project.name}"
version: "${project.version}"
website: "${project.url}"
api-version: "1.13"
authors:
  - JustEli
softdepend:
  - Vault
  - WorldGuard
  - mcMMO
  - MythicMobs
commands:
  coins:
    aliases:
      - coin
  withdraw: {}
