main: "${project.groupId}.${project.name}"
name: "${project.name}"
version: "${project.version}"
author: JustEli
website: "${project.url}"
softdepend: [Vault, WorldGuard, mcMMO]
api-version: "1.13"
commands:
  coins:
    aliases: [coin]
  withdraw:
